#!/usr/bin/env python3
# usage: $ oj generate-input 'python3 generate.py'
# usage: $ oj generate-input --hack-actual=./a.out --hack-expected=./naive 'python3 generate.py'
import random

# generated by oj-template v4.8.1 (https://github.com/online-judge-tools/template-generator)
def main():
    N = random.randint(2, 10 ** 5)  # TODO: edit here
    Q = random.randint(1, 10 ** 5)  # TODO: edit here
    l = [None for _ in range(Q)]
    r = [None for _ in range(Q)]
    S = ''.join([random.choice('ACGT') for _ in range(random.randint(N, N))])  # TODO: edit here
    for i in range(Q):
        ll = random.randint(1, 10 ** 5)  # TODO: edit here
        rr = random.randint(1, 10 ** 5)
        l[i] = min(ll, rr)  # TODO: edit here
        r[i] = max(ll, rr)  # TODO: edit here
    print(N, Q)
    print(S)
    for i in range(Q):
        print(l[i], r[i])

if __name__ == "__main__":
    main()